CREATE TABLE  `2012Grad_Products` (
 `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 `created_at` DATETIME NOT NULL ,
 `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 `Name` VARCHAR( 255 ) NOT NULL ,
 `Price` DOUBLE NOT NULL DEFAULT  '0.0',
 `Description` VARCHAR( 4000 ) NULL ,
 `Quantity` INT NOT NULL DEFAULT  '1',
 `Keywords` VARCHAR( 500 ) NULL
) ENGINE = InnoDB  ;